import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css"
				/>
			</Head>
			<main className={styles.main}>
				<header className="grid grid-cols-3 bg-white p-5 md:px-10">
					<div className="relative flex items-center h-10 cursor-pointer my-auto">
						<Link
							href="/"
							className="logo current"
						>
							<Image
								src="/nara-black.svg"
								width="60"
								height="18"
								alt="nara"
							></Image>
						</Link>
					</div>
				</header>
				<div className="relative max-w-5xl mx-auto pt-6 sm:pt-20 lg:pt-32 px-4 sm:px-6 md:px-8">
					<div className="flex justify-center pb-10">
						<Link
							href="https://www.producthunt.com/posts/nara?utm_source=badge-featured&amp;utm_medium=badge&amp;utm_souce=badge-nara"
							target="_blank"
						>
							{/* eslint-disable-next-line */}
							<img
								src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=381965&amp;theme=light"
								alt="Nara - The personalized nutritionist in your pocket | Product Hunt"
								className="w-60 h-10"
							/>
						</Link>
					</div>
					<h1 className="font-itcbold text-black  text-4xl sm:text-5xl lg:text-6xl tracking-tight text-center">
						Your AI nutrition assistant
					</h1>
					<p className="font-itc font-bold mt-6 text-md sm:text-lg md:text-xl text-[#818181] text-center max-w-3xl mx-auto">
						Ask questions and get personalized suggestions 24/7 from your AI
						nutrition coach through SMS (only US &amp; Canada for now). Get
						recipe suggestions, dine-out options, and food delivery
						recommendations tailored to your preferences.
					</p>
					<div className="mx-auto w-full max-w-md px-2.5 sm:px-0 mt-10">
						<div className="mt-3">
							<Link
								className="font-itc block w-full py-3 px-4 rounded-md bg-[#0096F7] text-white text-center"
								href="https://buy.stripe.com/8wMg0e9vu00v2645ms"
							>
								Start your 7-day free trial
							</Link>
						</div>
						<div className="mt-14">
							<Image
								alt="Picture of a phone"
								src="/_next/image?url=%2Fheader_phone_mockup.png&amp;w=828&amp;q=75"
								width="400"
								height="800"
								decoding="async"
								data-nimg="1"
								className="object-center w-full"
								loading="lazy"
								style={{ color: 'transparent' }}
							/>
						</div>
						<div>
							<Link href="https://www.ycombinator.com/launches/ I9f-nara-the-personalized-nutritionist-in-your-pocket">
								{/* eslint-disable-next-line */}
								<img
									className="mx-auto w-3/5"
									src="/backed-by-yc.svg"
									alt="backed-by-yc"
								/>
							</Link>
						</div>
						<div className="pt-6">
							<Link
								href="https://www.ycombinator.com/launches/I9f-nara-the-personalized-nutritionist-in-your-pocket"
								target="_blank"
							>
								{/* eslint-disable-next-line */}
								<img
									alt="Launch YC: 🔘 Nara: The personalized nutritionist in your pocket"
									src="https://www.ycombinator.com/launches/I9f-nara-the-personalized-nutritionist-in-your-pocket/upvote_embed.svg"
									className="mx-auto w-3/5"
								/>
							</Link>
						</div>
					</div>
				</div>
				<section className="mt-20 mb-16 sm:mt-32 md:mt-40">
					<h1 className="font-itcbold text-black text-3xl sm:text-4xl lg:text-5xl tracking-tight text-center">
						Your healthy assistant
					</h1>
					<div className="pt-10 lg:w-2/3 mx-auto grid lg:grid-cols-3 gap-x-8 gap-y-8 place-items-center">
						<div className=" overflow-hidden shadow-lg rounded-xl lg:max-w-7xl md:max-w-lg max-w-md">
							<div
								id="SectionImg1"
								className="relative h-80 w-full"
							></div>
							<div className="p-6">
								<h3 className="font-itcmedium">Your New Healthy Friend</h3>
								<p className="mt-2 font-itc text-sm text-[#818181]">
									Nara suggests the best option from the menu to eat in a
									restaurant according to your meal plan.
								</p>
							</div>
						</div>
						<div className="shadow-lg over rounded-xl lg:max-w-7xl md:max-w-lg max-w-md">
							<div
								id="SectionImg2"
								className="relative h-80 w-full"
							></div>
							<div className="p-6">
								<h3 className="font-itcmedium">Your New Healthy Friend</h3>
								<p className="mt-2 font-itc text-sm text-[#818181]">
									Nara suggests the best option from the menu to eat in a
									restaurant according to your meal plan.
								</p>
							</div>
						</div>
						<div className="shadow-lg overflow-hidden rounded-xl lg:max-w-7xl mgd:max-w-lg max-w-md">
							<div
								className="relative h-80 w-full "
								id="SectionImg3"
							></div>
							<div className="p-6">
								<h3 className="font-itcmedium">Your New Healthy Friend</h3>
								<p className="mt-2 font-itc text-sm text-[#818181]">
									Nara suggests the best option from the menu to eat in a
									restaurant according to your meal plan.
								</p>
							</div>
						</div>
					</div>
				</section>
				<footer className="p-4 bg-white rounded-lg shadow md:px-6 md:py-8">
					<div className="sm:flex sm:items-center sm:justify-between">
						<Link
							href=""
							className="flex items-center mb-4 sm:mb-0"
						>
							{/* eslint-disable-next-line */}
							<img
								src="/nara-black.svg"
								className="h-4 mr-3"
								alt="Nara Logo"
							/>
						</Link>
						<ul className="font-itc flex flex-wrap items-center mb-6 text-sm text-black sm:mb-0">
							<li>
								<Link
									href="#"
									className="mr-4 hover:underline md:mr-6 "
								>
									About
								</Link>
							</li>
							<li>
								<Link
									href="/privacy_policy"
									target="_blank"
									rel="noopener"
									className="mr-4 hover:underline md:mr-6"
								>
									Privacy Policy
								</Link>
							</li>
							<li>
								<Link
									href="/terms"
									target="_blank"
									rel="noopener"
									className="mr-4 hover:underline md:mr-6 "
								>
									Terms of Service
								</Link>
							</li>
							<li>
								<Link
									href="mailto:founders@trynara.com"
									className="hover:underline"
								>
									Contact
								</Link>
							</li>
						</ul>
					</div>
				</footer>
			</main>
		</>
	);
}
